"""add turns.sent_message_id

Revision ID: 3a81bf584b76
Revises: fe2d0d7647c3
Create Date: 2026-09-19 14:48:57.992610

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a81bf584b76'
down_revision: Union[str, None] = 'fe2d0d7647c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('sent_message_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'sent_message_id')
    # ### end Alembic commands ###
