"""initial schema: inbound_events, turns

Revision ID: fe2d0d7647c3
Revises: 
Create Date: 2026-09-19 14:15:43.968781

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2d0d7647c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # id columns use BigInteger().with_variant(Integer, "sqlite"): SQLite
    # only auto-populates a PK declared as plain INTEGER PRIMARY KEY (its
    # ROWID-alias trick) — a bare BigInteger silently leaves `id` NULL on
    # SQLite and every insert fails NOT NULL. Postgres still gets a real
    # BIGINT/BIGSERIAL-equivalent column, matching DESIGN.md Section 6.2.
    id_type = sa.BigInteger().with_variant(sa.Integer(), "sqlite")
    op.create_table('inbound_events',
    sa.Column('id', id_type, autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inbound_events_contact_received', 'inbound_events', ['contact_id', 'received_at'], unique=False)
    op.create_table('turns',
    sa.Column('id', id_type, autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Text(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('inbound_message_id', sa.Text(), nullable=False),
    sa.Column('stage_before', sa.Text(), nullable=False),
    sa.Column('stage_after', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('tool_output', sa.JSON(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('regenerated', sa.Boolean(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('send_mode', sa.Text(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['inbound_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'inbound_message_id', name='uq_turns_contact_message')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turns')
    op.drop_index('ix_inbound_events_contact_received', table_name='inbound_events')
    op.drop_table('inbound_events')
    # ### end Alembic commands ###
